django_secret_key:
networks:
  - name: ethereum
    private_key:
    decimals: 18
    explorer_api_key:
    explorer_api_url: https://api.etherscan.io/
    num: 2
    node:
    swap_contract: '0xF6d61CECa23639ECebEEeCaafA4F90e5ddD6FF07'
    symbol: ETH
  - name: smart_chain
    private_key:
    decimals: 18
    explorer_api_key:
    explorer_api_url: https://api.bscscan.com/
    num: 1
    node: https://bsc-dataseed.binance.org/
    swap_contract: '0x17c46590f833d314b5Ad799B7b386d8fdf630796'
    symbol: BNB
relayers:
  - 127.0.0.1:8001
