version: "3.8"

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      multisig-bridge-validator:

  scanner:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/scanner.Dockerfile
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      multisig-bridge-validator:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    restart: unless-stopped
    networks:
      multisig-bridge-validator:
  celery:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/validator_celery.Dockerfile
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      multisig-bridge-validator:

networks:
  multisig-bridge-validator: