  
- name: Tear down existing services
  docker_compose:
    project_src: "{{ worker_home_path }}/multisig_bridge"
    files: "{{ docker_compose_file }}"
    state: absent

- name: Create and start services
  docker_compose:
    project_src: "{{ worker_home_path }}/multisig_bridge"
    files: "{{ docker_compose_file }}"
    build: yes
    restarted: yes
    state: present

- name: Make migrations (relayer)
  command: 
    cmd: > 
      docker-compose 
      -f {{ worker_home_path}}/multisig_bridge/{{ docker_compose_file }} 
      exec {{ python_app }} python manage.py makemigrations relayer

- name: Make migrations (validator)
  command: 
    cmd: > 
      docker-compose 
      -f {{ worker_home_path}}/multisig_bridge/{{ docker_compose_file }}
      exec {{ python_app }} python manage.py makemigrations validator

- name: Make migrations (bot)
  command: 
    cmd: > 
      docker-compose 
      -f {{ worker_home_path}}/multisig_bridge/{{ docker_compose_file }}
      exec {{ python_app }} python manage.py makemigrations bot

- name: Migrate DB
  command: 
    cmd: > 
      docker-compose 
      -f {{ worker_home_path}}/multisig_bridge/{{ docker_compose_file }}
      exec {{ python_app }} python manage.py migrate

- name: Create and start services
  docker_compose:
    project_src: "{{ worker_home_path }}/multisig_bridge"
    files: "{{ docker_compose_file }}"
    restarted: yes
      
